abbreviate.far: abbreviate.grm local/common.far local/ordinals.far local/factorize.far text_norm/lex/abbreviate_words.txt text_norm/lex/abbreviate_if_preceded_wNumber.txt text_norm/lex/abbreviate_if_followed_byNumber.txt text_norm/lex/kjordaemi_abbr.txt text_norm/lex/abbr_periods.txt
	thraxcompiler --input_grammar=$< --output_far=$@

