#!/usr/bin/env python3
#-*- coding: utf-8 -*-

# Replaces some abbreviations.
import sys,re

if (len(sys.argv) < 3):
	print("Need 2 arguments: input file and output file!")
	sys.exit()

with open(sys.argv[1],'r',encoding='utf-8') as in_file:
    text = in_file.read().strip()
out_file = open(sys.argv[2], 'w',encoding='utf-8')

text = re.sub(" amk "," að minnsta kosti ",text)
text = re.sub(" dr "," doktor ",text)
text = re.sub(" etv "," ef til vill ",text)
text = re.sub(" frh "," framhald ",text)
text = re.sub(" fyrrv "," fyrrverandi ",text)
text = re.sub(" mas "," meira að segja ",text)
text = re.sub(" ma "," meðal annars ",text)
text = re.sub(" nk "," næstkomandi ",text)
text = re.sub(" nr "," númer ",text)
text = re.sub(" osfrv "," og svo framvegis ",text)
text = re.sub(" oþh "," og þess háttar ",text)
text = re.sub(" pr "," per ",text)
text = re.sub(" sbr "," samanber ",text)
text = re.sub(" skv "," samkvæmt ",text)
text = re.sub(" ss "," svo sem ",text)
text = re.sub(" stk "," stykki ",text)
text = re.sub(" td "," til dæmis ",text)
text = re.sub(" tam "," til að mynda ",text)
text = re.sub(" uþb "," um það bil ",text)
text = re.sub(" utanrrh "," utanríkisráðherra ",text)
text = re.sub(" þáv "," þáverandi ",text)
text = re.sub(" þús "," þúsund ",text)
text = re.sub(" þeas "," það er að segja ",text)
text = re.sub(" aa "," a a ",text)
text = re.sub(" aaa "," a a a ",text)
text = re.sub(" adhd "," a d h d ",text)
text = re.sub(" ags "," a g s ",text)
text = re.sub(" bbc "," b b c ",text)
text = re.sub(" bhm "," b h m ",text)
text = re.sub(" bs "," b s ",text)
text = re.sub(" bsrb "," b s r b ",text)
text = re.sub(" dv "," d v ",text)
text = re.sub(" eb "," e b ",text)
text = re.sub(" ebe "," e b e ",text)
text = re.sub(" ehf "," e h f ",text)
text = re.sub(" ees "," e e s ",text)
text = re.sub(" esb "," e s b ",text)
text = re.sub(" esí "," e s í ",text)
text = re.sub(" fka "," f k a ",text)
text = re.sub(" fme "," f m e ",text)
text = re.sub(" gps "," g p s ",text)
text = re.sub(" hf "," h f ",text)
text = re.sub(" hpv "," h p v ",text)
text = re.sub(" hs "," h s ",text)
text = re.sub(" hss "," h s s ",text)
text = re.sub(" http "," h t t p ",text)
text = re.sub(" https "," h t t p s ",text)
text = re.sub(" ifs "," i f s ",text)
text = re.sub(" imf "," i m f ",text)
text = re.sub(" ísí "," í s í ",text)
text = re.sub(" kb "," k b ",text)
text = re.sub(" kgb "," k g b ",text)
text = re.sub(" kí "," k í ",text)
text = re.sub(" lh "," l h ",text)
text = re.sub(" ls "," l s ",text)
text = re.sub(" lsh "," l s h ",text)
text = re.sub(" lsr "," l s r ",text)
text = re.sub(" lss "," l s s ",text)
text = re.sub(" mbl"," m b l ",text)
text = re.sub(" mfs "," m f s ",text)
text = re.sub(" mh "," m h ",text)
text = re.sub(" mmr "," m m r ",text)
text = re.sub(" mnd "," m n d ",text)
text = re.sub(" mp "," m p ",text)
text = re.sub(" mpa "," m p a ",text)
text = re.sub(" mr "," m r ",text)
text = re.sub(" ms "," m s ",text)
text = re.sub(" nfs "," n f s ",text)
text = re.sub(" npa "," n p a ",text)
text = re.sub(" nsa "," n s a ",text)
text = re.sub(" oecd "," o e c d ",text)
text = re.sub(" ohf "," o h f ",text)
text = re.sub(" psa "," p s a ",text)
text = re.sub(" sa "," s a ",text)
text = re.sub(" sáá "," s á á ",text)
text = re.sub(" sdr "," s d r ",text)
text = re.sub(" sf "," s f ",text)
text = re.sub(" sfr "," s f r ",text)
text = re.sub(" sík "," s í k ",text)
text = re.sub(" sms "," s m s ",text)
text = re.sub(" sp "," s p ",text)
text = re.sub(" srú "," s r ú ",text)
text = re.sub(" tf "," t f ",text)
text = re.sub(" th "," t h ",text)
text = re.sub(" tr "," t r ",text)
text = re.sub(" vg "," v g ",text)
text = re.sub(" vr "," v r ",text)
text = re.sub(" vs "," v s ",text)
text = re.sub(" vto "," v t o ",text)
text = re.sub(" þssí "," þ s s í ",text)
text = re.sub(" öbí "," ö b í ",text)

print(text, file=out_file)
out_file.close()
